---
title: Bestuur een verkeerslicht met EduBlocks
hero_image: images/banner.png
description: Leer een verkeerslicht te besturen en te programmeren met behulp van
  EduBlocks
listed: false
copyedit: false
version: 4.1
last_tested: 2018-11-20
steps:
- title: Inleiding
  completion: engaged
- title: Verbind de LED's
- title: Bedien de LED's
  completion: internal
- title: Verkeerslichten volgorde
