---
title: Traffic Lights with EduBlocks
hero_image: images/banner.png
description: Leer een verkeerslicht te besturen en te programmeren met behulp van EduBlocks
listed: false
copyedit: false
version: 4.1
last_tested: 2018-11-20
steps:
  - 
    title: Inleiding
  - 
    title: Connect the LEDs
  - 
    title: Control the LEDs
  - 
    title: Traffic lights sequence
