---
title: Bestuur een verkeerslicht met EduBlocks
hero_image: afbeeldingen / banner.png
description: Leer een verkeerslicht te besturen en te programmeren met behulp van EduBlocks
theme: rood
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: programmeren-0, computer techniek-0
interests: "computergebruik"
technologies: "elektronica, computer techniek, python, edublocks"
site_areas: ""
steps:
  - 
    title: Introductie
  - 
    title: Wat heb je nodig
  - 
    title: Verbind de LED's
  - 
    title: Bestuur de LED's
  - 
    title: Verkeerslicht volgorde
