---
title: Traffic Lights with EduBlocks
hero_image: images/banner.png
description: Learn to control traffic light LEDs and code a traffic lights sequence
  using EduBlocks
listed: false
copyedit: false
version: 4.1
last_tested: 2018-11-20
steps:
- title: Introduction
- title: Connect the LEDs
- title: Control the LEDs
- title: Traffic lights sequence
