---
title: EduBlocks के साथ एक ट्रैफिक लाइट्स अनुक्रम को नियंत्रित करें
hero_image: छवियों / banner.png
description: ट्रैफिक लाइट एल ई डी को नियंत्रित करने और एडुब्लॉक्स का उपयोग कर ट्रैफिक लाइट अनुक्रम को नियंत्रित करने के बारे में जानें
theme: लाल
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: प्रोग्रामिंग -0, फिज़-कंप-0
interests: "शारीरिक कंप्यूटिंग"
technologies: "इलेक्ट्रॉनिक्स, भौतिक कंप्यूटिंग, अजगर, edublocks"
site_areas: ""
steps:
  - 
    title: परिचय
  - 
    title: तुम क्या आवश्यकता होगी
  - 
    title: एलआईडी कनेक्ट करें
  - 
    title: एल ई डी को नियंत्रित करें
  - 
    title: ट्रैफिक लाइट अनुक्रम
