---
title: एड्यू ब्लोक्स  के साथ ट्रैफिक लाइट
hero_image: images/banner.png
description: ट्रैफिक लाइट एल. ई. डी. को नियंत्रित करने और EduBlocks का उपयोग करके ट्रैफिक लाइट अनुक्रम को नियंत्रित करने के बारे में जानें
listed: false
copyedit: false
version: 4.1
last_tested: 2018-11-20
steps:
  - 
    title: भूमिका
  - 
    title: एल. ई. डी. को जोड़े
  - 
    title: एल. ई. डी. को नियंत्रित करें
  - 
    title: ट्रैफिक लाइट अनुक्रम
