---
title: Traffic Lights with EduBlocks
hero_image: images / banner.png
description: EduBlocksを使用して信号灯のLEDを制御し、信号灯シーケンスをコードする方法を学ぶ
listed: false
copyedit: false
version: 4.1
last_tested: 2018-11-20
steps:
  - 
    title: 前書き
  - 
    title: Connect the LEDs
  - 
    title: Control the LEDs
  - 
    title: Traffic lights sequence
