---
title: Traffic Lights with EduBlocks
hero_image: изображения / banner.png
description: Научете как да управлявате светодиодите със светофар и да кодирате последователността на светофарите с помощта на EduBlocks
listed: false
copyedit: false
version: 4.1
last_tested: 2018-11-20
steps:
  - 
    title: Въведение
  - 
    title: Connect the LEDs
  - 
    title: Control the LEDs
  - 
    title: Traffic lights sequence
