---
title: Traffic Lights with EduBlocks
hero_image: images/banner.png
description: Mit Hilfe von EduBlocks wirst du lernen Ampel-LEDs zu steuern und eine Ampelsequenz zu programmieren
listed: false
copyedit: false
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Einleitung
  - 
    title: Was du brauchen wirst
  - 
    title: Verbinde die LEDs
  - 
    title: Steuere die LEDs
