---
title: Traffic Lights with EduBlocks
hero_image: images / banner.png
description: Tanuld meg, hogy irányíthatja a közlekedési lámpák LED-jeit és kódolja a közlekedési lámpák sorrendjét az EduBlocks segítségével
listed: false
copyedit: false
version: 4.1
last_tested: 2018-11-20
steps:
  - 
    title: Bevezetés
  - 
    title: Connect the LEDs
  - 
    title: Control the LEDs
  - 
    title: Traffic lights sequence
