---
title: Contrôler une séquence de feux de circulation avec EduBlocks
hero_image: images / banner.png
description: Apprenez à contrôler les voyants du feu et à coder une séquence de feux de circulation à l'aide d'EduBlocks
theme: rouge
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: programmation-0, phys-comp-0
interests: "informatique physique"
technologies: "électronique, informatique physique, python, édublocks"
site_areas: ""
steps:
  - 
    title: introduction
  - 
    title: Ce dont tu auras besoin
  - 
    title: Connectez les LED
  - 
    title: Contrôler les LED
  - 
    title: Séquence de feux de circulation
