---
title: Feux de signalisation avec EduBlocks
hero_image: images / banner.png
description: Apprends à contrôler les LEDs du feu et à coder une séquence de feux de signalisation avec EduBlocks
listed: false
copyedit: false
version: 4.1
last_tested: 2018-11-20
steps:
  - 
    title: Introduction
  - 
    title: Connexion des LEDs
  - 
    title: Contrôle des LEDs
  - 
    title: Séquence de feux de circulation
