---
title: Traffic Lights with EduBlocks
hero_image: images / banner.png
description: Impara a controllare i semafori a LED e codifica una sequenza di semafori utilizzando EduBlocks
listed: false
copyedit: false
version: 4.1
last_tested: 2018-11-20
steps:
  - 
    title: introduzione
  - 
    title: Connect the LEDs
  - 
    title: Control the LEDs
  - 
    title: Traffic lights sequence
