---
title: Controlla un semaforo con EduBlocks
hero_image: images/banner.png
description: Impara a controllare un semaforo a LED e programma una sequenza semaforica usando EduBlocks
listed: false
copyedit: false
version: 4.1
last_tested: 2018-11-20
steps:
  - 
    title: Introduzione
  - 
    title: Collega i LED
  - 
    title: Controlla i LED
  - 
    title: Sequenza del semaforo
